var risposte = [
	'Si',
	'No',
	'Impossibile',
	'Improbabile',
	'Certamente',
	'Ovvio',
	'Probabile',
	'Potrebbe essere straordinario',
	'Non essere ridicolo/a',
	'Creerà confusione',
	'Non cè nessuna garanzia',
	'Qualcuno ti aiuterà',
	'Abbandona le vecchie soluzioni',
	'La situazione non è chiara',
	'Cerca di concludere',
	'Non ignorare ciò che è ovvio',
	'Non precluderti nulla',
	'Fai una lista dei pro',
	'Fai una lista dei contro',
	'Potrebbero emergere altri problemi',
	'Non esitare',
	'Avere troppe alternative è un ostacolo come averne poche',
	'Sicuramente',
	'Non sarai deluso/a',
	'Capirai solo se ascolterai con attenzione',
	'Non sprecare il tuo tempo',
	'Sembra certo',
	'Valuta più alternative',
	'Non dubitarne',
	'Richiederà uno sforzo considerevole',
	'Potrà sembrarti difficile ma porterà dei risultati',
	'Si, ma non forzare le cose',
	'E" importante',
	'Gli esiti potrebbero essere sorprendenti',
	'Ci saranno dei contrattempi',
	'Il tempo porterà consiglio',
	'Non preoccuparti',
	'Ora puoi',
	'Fai qualcosa di diverso',
	'Resterà un dubbio',
	'Lascia perdere',
	'Parlane apertamente',
	'E" sconsigliabile',
	'Scoprirai tutto ciò che hai bisogno di sapere',
	'Le tue scelte coinvolgono altre persone',
	'E" quasi sicuro',
	'Rischia',
	'Non aspettare',
	'E" un buon momento per fare progetti',
	'Concentrati sul lavoro',
	'Goditi il momento',
	'Non rischiare',
	'E" il momento buono per cose nuove',
	'Scopri il significato delle cose e poi goditele',
	'Metti tutto nero su bianco, troverai la risposta',
	'Senza dubbio',
	'Non puoi fallire',
	'Guardati dalle trappole',
	'Pensa bene alle priorità',
	'L"esito sarà positivo',
	'L"esito sarà negativo',
	'Fidati della tua prima impressione',
	'Fai attenzione ai dettagli',
	'Crepi l"avarizia',
	'Dai priorità a ciò che è importante',
	'Ti rimarrà sempre nel cuore',
	'Prima finisci qualcos"altro',
	'Risparmia le energie',
	'Può essere una questione già risolta',
	'Impegnati al massimo',
	'Segui il consiglio degli esperti',
	'Mai',
	'Sempre',
	'Qualche volta',
	'Raramente',
	'Cerca sempre di migliorare',
	'Insisti e ce la farai',
	'Non sentirti in obbligo di agire troppo in fretta',
	'Tienilo per te',
	'Parlane con i tuoi genitori',
	'Parlane con i tuoi amici',
	'Sicuramente renderà le cose più interessanti',
	'Ne vale la pena',
	'Non ne vale la pena',
	'La famiglia è la cosa più importante',
	'Non preoccuparti di niente',
	'Non sarà sempre così',
	'Se proprio non resisti',
	'E" sicuro... sii entusiasta',
	'Non scendere a compromessi',
	'Procedi',
	'Non procedere',
	'Non ha importanza',
	'Fallo diventare una priorità',
	'Riconsidera il tuo atteggiamento',
	'La faccenda ti sta troppo a cuore per capire',
	'Prenditene cura',
	'Sarai felice di averlo fatto',
	'Non sarai felice di averlo fatto',
	'Dovrai scendere a compromessi'
]

function genera_risposta() {
	var random = Math.floor(Math.random() * (risposte.length));
	document.getElementById('random').innerHTML = risposte[random];
}