var domande = [
	'Sei pronto/a?',
	'Come ti chiami?',
	'Hai un soprannome? Se sì, quale?',
	'Quanti anni hai?',
	'Quando sei nato/a?',
	'Hai dei segni particolari?',
	'Hai fratelli? Se sì, come si chiamano? Che rapporto hai con loro?',
	'Dove sei nato/a?',
	'Quanto sei alto/a?',
	'Di che colore hai gli occhi?',
	'Di che colore hai i capelli?',
	'Di che misura sono le tue scarpe?',
	'Indossi occhiali da vista?',
	'Hai qualche piercing? Se sì, quanti e dove? Se no, ti piacerebbe farne qualcuno?',
	'Hai qualche tatuaggio? Se sì, quanti e dove? Se no, ti piacerebbe farne qualcuno?',
	'Hai qualche animale domestico? Se sì, quale? Se no, quale ti piacerebbe avere?',
	'Lavori? Se sì, ti piace il tuo lavoro? Se no, quale lavoro ti piacerebbe fare?',
	'Ti sei mai ubriacato/a? Se sì, in quale occasione?',
	'Ti sei mai innamorato/a? Se sì, di chi?',
	'Hai mai amato qualcuno al punto di piangere?',
	'Hai mai avuto incidenti in macchina? Se sì, come è avvenuto?',
	'Hai mai avuto incidenti in moto? Se sì, come è avvenuto?',
	'Bevi vino? Se sì, Vino rosso o Vino bianco?',
	'Coca Cola o Pepsi? E perché?',
	'Limonata o Aranciata? E perché?',
	'Caffè normale o macchiato? Zuccherato o amaro? Zucchero normale o di canna?',
	'Coperta o piumone? E perché?',
	'Lasciare o essere lasciati? E perché?',
	'Colore dei calzini?',
	'Numero preferito? E perché?',
	'Film preferito? E perché?',
	'Citazione preferita? E perché?',
	'Computer o Console? Se console, perché?',
	'Giorno della settimana preferito? E perché?',
	'Canzone preferita? E perché?',
	'Programma televisivo preferito? E perché?',
	'Telefilm preferito? E perché?',
	'Cartone preferito? E perché?',
	'Hai mai nuotato nudo/a? Se sì, dove? Se no, ti piacerebbe farlo?',
	'Cocktail preferito? E perché?',
	'Pratichi qualche sport? Se sì, quale? Se no, quale ti piacerebbe praticare?',
	'Quale sport ti piace vedere dal vivo? E perché?',
	'Quale sport ti piace vedere alla TV? E perché?',
	'Pasta o pizza? E perché?',
	'Come ti vedi da qui a 10 anni?',
	'Cosa fai quando ti senti giù di morale?',
	'Qual è la parolaccia che dici più spesso?',
	'Qual è la frase che dici più spesso?',
	'Qual è la cosa che odi di più? E perché?', 
	'Chi è che non sopporti? E perché?',
	'Qual è, secondo te, la cosa più bella che esiste? E perché?',
	'A che ora vai a dormire?',
	'Sei Destrorso/a o mancino/a?',
	'Credi nell’oroscopo? Se sì, che segno zodiacale sei? Qual è, invece, il tuo segno zodiacale cinese?',
	'Qual è il tuo punto debole?',
	'Qual è il tuo ricordo più brutto?',
	'Qual è il tuo ricordo più bello?',
	'Qual è Il tuo peggior difetto?',
	'Quale difetto ti attribuiscono?',
	'Di cosa hai paura?',
	'Hai un obiettivo? Se sì, quale?',
	'Qual è il tuo primo pensiero la mattina?',
	'Qual è il tuo ultimo pensiero prima di andare a letto?',
	'Qual è la prima cosa che guardi in una persona del sesso opposto? E perché?',
	'Qual è la qualità che cerchi in una persona del sesso opposto? E perché?',
	'Sai cantare? Se sì, ti va di cantare un pezzo a tuo piacimento? Se no, come quale cantante ti piacerebbe saper cantare?',
	'Credi in te stesso/a?',
	'Pensi di essere attraente?',
	'Vai d^accordo con i tuoi genitori?',
	'Suoni uno strumento?',
	'A che età il primo bacio?',
	'A che età la prima volta?',
	'Il tuo nome preferito? Invece quello che odi?',
	'Meglio tentare ma poi pentirsi o non tentare e rimpiangerlo?',
	'Credi nel destino?',
	'Credi in Dio?',
	'Inverno o estate? E perché?',
	'Mare o montagna? E perché?',
	'Sai chiedere scusa?',
	'Sei permaloso/a?',
	'Cosa cambieresti di te? E perché?',
	'Hai mai rubato? Se sì, cosa?',
	'Ami il rischio?',
	'Sai stare solo/a?',
	'Sei felice?',
	'Vuoi avere figli?',
	'Matrimonio o convivenza? E perché?',
	'Essere o apparire?',
	'L^emozione che più ti tocca?',
	'Cosa non faresti mai? E perché?',
	'Quali sarebbero i tuoi 3 desideri al genio della lampada? (Non vale chiedere desideri infiniti o robe simili)',
	'Dormi con le porte dell’armadio aperte o chiuse?',
	'Prendi gli shampoo e i saponi dagli hotel?',
	'Dormi dentro o fuori dalle lenzuola?',
	'Hai mai rubato un cartello stradale?',
	'Utilizzi post-it?',
	'Hai mai tagliato dei coupon per poi non usarli?',
	'Preferiresti essere attaccato/a da un orso o uno sciame di api?',
	'Hai le lentiggini? Se no, ti piacerebbe averle?',
	'Sorridi sempre nelle foto?',
	'Qual è il tuo più grande dolore?',
	'Ti è mai capitato di contare i passi mentre cammini?',
	'Hai mai fatto la pipì in un luogo che non sia il bagno? Se sì, dove? E la cacca?',
	'Ti sei messo a ballare anche se non c’era musica?',
	'Mastichi le penne o le matite?',
	'Quanto è grande il tuo letto? Soddisfa le tue esigenze?',
	'Qual è la tua canzone della settimana?',
	'Per te va bene se i ragazzi indossano il rosa? Se no, perché?',
	'Guardi ancora i cartoni animati? Se sì, quali? Se no, perché?',
	'Quale è il tuo film preferito? E perché?',
	'Dove nasconderesti un tesoro se ne avessi uno?',
	'Qual è il tuo cibo preferito?',
	'Che film guarderesti più e più volte? E perché?',
	'L^ultima persona che hai baciato/ti ha baciato?',
	'Poseresti mai nudo/a per una rivista?',
	'Quando è stata l^ultima volta che hai scritto una lettera a qualcuno?',
	'Sai cambiare l^olio in una macchina?',
	'Hai mai ricevuto una multa per eccesso di velocità? Se sì, a quanto viaggiavi?',
	'Se mai rimasto/a senza benzina? Se sì, dove ti trovavi?',
	'Qual è il tuo panino preferito?',
	'Qual è, secondo te, la cosa migliore da mangiare a colazione? E perché?',
	'Sei pigro/a?',
	'Quando eri piccolo/a, da cosa ti vestivi ad Halloween?',
	'Quante lingue sai parlare?',
	'Sei testardo/a?',
	'Hai paura dell’altezza?',
	'Canti in macchina? E sotto la doccia?',
	'Hai mai usato una pistola?',
	'L^ultima volta che ti hanno fotografato?',
	'Pensi che i musical siano ridicoli? Se sì, perché?',
	'Pe te il Natale è stressante? Se sì, perché?',
	'Qual è il tuo frutto preferito? Verdura preferita?',
	'Qual è il lavoro che volevi fare da piccolo/a? E perché?',
	'Credi ai fantasmi?',
	'Hai mai avuto la sensazione di Deja-vu?',
	'Hai mai partecipato ad un concerto? Se sì, di quale artista? Se no, a quale ti piacerebbe partecipare?',
	'Nike o Adidas?',
	'Hai mai preso lezioni di ballo? Se sì, quale tipologia? Se no, ti piacerebbe?',
	'Che lavoro vuoi che faccia il tuo/la tua futuro/a coniuge?',
	'Sai arricciare la lingua?',
	'Hai mai pianto perché eri felice? Se sì, in quale occasione?',
	'Tè caldo o tè freddo?',
	'Sai nuotare?',
	'Sei paziente?',
	'Hai mai vinto un concorso? Se sì, quale? Se no, a quale concorso ti piacerebbe partecipare?',
	'Hai mai fatto un intervento di chirurgia plastica? Se sì, a cosa? Se no, ti piacerebbe fartene uno?',
	'Olive nere o verdi?',
	'Vuoi sposarti? Se sì, a che età? Se no, perché? Se sposato, da quanto tempo siete sposati?',
	'Piangi e fai capricci fino a quando non ottieni quel che vuoi?',
	'Hai figli?',
	'Vuoi bambini?',
	'Qual è il tuo colore preferito?',
	'Ti manca qualcuno in questo momento? Se sì, chi?',
	'Hai mai rotto qualcosa in casa? Se sì, cosa e come?',
	'Hai mai fatto il bagno con le onde molto alte?',
	'Sei mai caduto/a dalle scale?',
	'Qual è il tuo animale preferito?',
	'Qual è la tua fiaba preferita? E perché?',
	'Hai mai pianto in pubblico? Se sì, perché?',
	'Hai mai cantato/ballato in pubblico? Se sì, cosa?',
	'Sei fidanzato/a? Se sì, da quanto? Se no, sei innamorato/a?',
	'Sai giocare a calcio? E a basket?',
	'Qual è il nome del tuo migliore amico? E della tua migliore amica?',
	'Qual è la tua materia preferita? E perché?',
	'Quale stazione radio ascolti di più?',
	'Che classe fai?',
	'Hai mai risposto a 100 domande consecutivamente?',
	'Qual è il tuo sogno più recente?',
	'Qual è stato il tuo sogno più strano?',
	'Qual è stato il tuo peggior incubo?',
	'Qual è stata la più grande cazzata che tu abbia mai fatto?',
	'Hai mai fatto after? Se sì, con chi? Se no, con chi ti piacerebbe farlo?',
	'Ginnastica ritmica o artistica? E perché?',
	'Calcio o calcetto? E perché?',
	'MC Donald^s o Burger king? E perché?',
	'Qual è stata la miglior frase che tu abbia mai sentito?',
	'Diresti in questo momento la prima cosa che ti viene in mente?',
	'Qual è il tuo gusto di gelato preferito?',
	'Qual è il tuo gusto di pizza preferito?',
	'Pioggia o neve? E perché?',
	'Mare o montagna? E perché?',
	'Estate o inverno? E perché?',
	'Hai mai dormito con un ragazzo/a? Se sì, con chi? Se no, con chi ti piacerebbe farlo?',
	'Hai mai comprato da un venditore ambulante? Se sì, cosa?',
	'Che squadra di calcio tifi? E perché?',
	'Qual è il primo videogioco a cui hai giocato?',
	'Qual è il primo canale YouTube a cui ti sei iscritto/a?',
	'Qual è il tuo canale televisivo preferito? E perché?',
	'Qual è stato il primo soprannome che hai dato a un tuo amico? E a una tua amica?',
	'Qual è stato il primo soprannome che ti hanno dato?',
	'Mamma o papà? E perché?',
	'Nonno o nonna? E perché?',
	'Preferisci avere 1 banconota da €5 o 5 monetine da €1? E perché?',
	'Hai mai fatto bungie jumping? Se sì, come è stato? Se no, ti piacerebbe farlo?',
	'Ti piace viaggiare?',
	'Che cosa fai quando ti annoi?',
	'Sei mai stato/a in un parco divertimenti? Se sì, quale? Se no, a quale ti piacerebbe andare?',
	'Manga o anime? E perché?',
	'Pranzo o cena? E perché?',
	'Apple o Android? E perché?',
	'Hai mai mangiato cibi esotici? Se sì, quali?',
	'Sei mai stato/a all^estero? Se sì, dove? Se no, dove ti piacerebbe andare?',
	'TV o YouTube? E perché?',
	'Libro cartaceo o digitale? E perché?',
	'Colazione o merenda? E perché?',
	'Gelato artigianale o confezionato? E perché?',
	'Fumi? Se sì, da quanto tempo?',
	'Hai mai bevuto superalcolici? Se sì, quali?',
	'Hai mai assunto sostanze stupefacenti? Se sì, quali?',
	'Che ore sono?',
	'Sprite o Fanta?',
	'Acqua naturale o gassata?',
	'Doccia calda o doccia fredda?',
	'Qual è l^insalata che più ti piace?',
	'Preferisci dare o ricevere?',
	'Hai mai fatto il bagno nel mare di notte?',
	'Qual è il tuo cibo straniero preferito? ',
	'Qual è il tuo fiore preferito?',
	'Ristorante o fast-food?',
	'Qual è il negozio che sceglieresti per spendere tutti i soldi di una carta di credito?',
	'Come si chiama l^amico/a che vive più lontano da te? Dove e quando l’hai conosciuto/a?',
	'Quale lavoro non vorresti mai fare? E perché?',
	'Ti piace stare al centro dell^attenzione?',
	'Per te il cellulare è indispensabile? Se sì, perché?',
	'Quanti messaggi ricevi in un giorno?',
	'Chi è l’ultima persona con cui hai litigato? E perché avete litigato?',
	'A cosa stai pensando in questo momento?',
	'Per te esiste l’amicizia tra maschio e femmina?',
	'Quanto conta la bellezza in una persona? E il fisico?',
	'Qual è stato l’ultimo CD che hai comprato? E l’ultimo DVD?',
	'Qual è lo scherzo più cattivo che hai mai fatto? E quello più cattivo che hai mai ricevuto?',
	'Bagno o doccia?',
	'Sole o pioggia?',
	'Natale o Capodanno?',
	'Qual è il tuo attore preferito?',
	'Credi nell’aldilà? Se sì, cosa c^è secondo te? Se no, cosa credi ci possa essere dopo la morte?',
	'Ti ritieni una persona fortunata? Se sì, per cosa?',
	'Qual è il paesaggio più bello che hai mai visto?',
	'Hai un sogno ricorrente? Se sì, ti va di raccontarlo?',
	'Chi è la persona più pazza che conosci?',
	'Se ti regalassero €100.000 gireresti nudo/a per la città?',
	'Hai mai picchiato qualcuno/a?',
	'Qual è il tuo social preferito? E perché?',
	'Quando ti sei sentito/a più a disagio?',
	'Qual è la città in cui abiteresti volentieri? E perché?',
	'Qual è il mezzo di trasporto che usi abitualmente? E perché?',
	'Hai paura di volare?',
	'Sei mai stato/a tradito/a? Se sì, da chi?',
	'Quali sono i tuoi giochi da tavolo preferiti?',
	'Qual è il tuo ricordo d’infanzia più bello?',
	'Litighi spesso con i tuoi genitori? Se sì, per cosa?',
	'Quante bugie hai detto giocando a SocialLife? Se le hai dette, a quali domande?',
	'Ti ho annoiato con questo gioco?',
	'Ti piacerebbe avere il file di questo gioco?',
	'Con chi ti piacerebbe giocare a SocialLife?',
	'Quale domanda vuoi che venga inserita in SocialLife?'
]

function genera_domanda() {
	var random = Math.floor(Math.random() * (domande.length));
	document.getElementById('random').innerHTML = domande[random];
}